### ISSUE TITLE
Add link to codeforbtv.org/projects/expunge-vt web page for Chrome extension

### ISSUE THREAD

**Issue by scottfvt** [codeforbtv/expunge-vt#116]
Put the following link on the codeforbtv.org/projects/expunge-vt web page: https://chrome.google.com/webstore/detail/expungevt/kkooclhchngcejjphmbafbkkpnaimadn. Put the link in a box on the right-hand side above the current Project Details box.

**Comment by doub1ejack** [comment]
All set!

![image](https://user-images.githubusercontent.com/1809882/73558772-dd8f7f80-4421-11ea-808a-cf2fc3283423.png)
