### ISSUE TITLE
Create and style form menu

### ISSUE THREAD

**Issue by jakedurell** [codeforbtv/expunge-vt#17]

**Comment by terriann** [comment]
This should be added to `formMenu/index.html`

Chalkboard from today's meetup:
![IMG_8217](https://user-images.githubusercontent.com/316632/57340606-8794e200-7104-11e9-89e7-e985f7dfdaa9.JPG)

**Comment by jakedurell** [comment]
This also needs an html multi-select box which adds everything that was generated, and allows the user to add or remove line items. This would be used to help generate the cover letter, certificate of service, and possibly a summary sheet for the Clinic's files about what was done.

**Comment by jakedurell** [comment]
This is the Petitioner info we need:

![image](https://user-images.githubusercontent.com/39913522/57371813-c907aa80-7161-11e9-881e-3a1ccd549da2.png)

**Comment by jakedurell** [comment]
I also just created a google doc called "forms and fields" which summarizes all the forms we will need and the fields we will use:

https://docs.google.com/spreadsheets/d/1lXoWphWmqI1i2HpVoX-u1cNZkxfKzX39b4cfbCwuKf0/edit#gid=0
