### ISSUE TITLE
Bugs as of 18-Jun

### ISSUE THREAD

**Issue by scottfvt** [codeforbtv/expunge-vt#50]
1. Use regex instead of replace function when parsing description fields for "/"
2. Put outline style for Name, DOB, and Address when editing.

**Comment by jeremybrault** [comment]
#2 is implemented in https://github.com/codeforbtv/expunge-vt/pull/63

**Comment by jeremybrault** [comment]
@jakedurell Is number 1 completed?

**Comment by jeremybrault** [comment]
This work has been completed.
