### ISSUE TITLE
Generating same form of petition for different counts - same county.

### ISSUE THREAD

**Issue by scottfvt** [codeforbtv/expunge-vt#56]
Discuss the method of generating the same form of a petition for different counts in the same county.

**Comment by jeremybrault** [comment]
An initial pass is completed for this in: https://github.com/codeforbtv/expunge-vt/pull/60. 

**To test:** 
Add counts from multiple dockets.
Mark them as the same filing type.
View Filings page.
Then use the checkbox at the top of the page labeled "Group Counts from Multiple Dockets" to toggle between grouped and ungrouped petitions.

We should add some logic to hide or disable this option if there is only 1 docket number present in the counts.

**Comment by jeremybrault** [comment]
Merged in https://github.com/codeforbtv/expunge-vt/pull/60
