### ISSUE TITLE
Add detail to CSV

### ISSUE THREAD

**Issue by jakedurell** [codeforbtv/expunge-vt#88]
On each row more info including...  Date, Pro se or not, etc...

**Comment by jeremybrault** [comment]
@jakedurell What did you mean by "Date". And could you list all of the fields you'd like to see added besides the two you listed here. Thanks!

**Comment by jakedurell** [comment]
The spreadsheet is sufficient for now @jeremybrault. When there's a clear direction on preserving records, we'll have stories for that.
